/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentList: typeof import('./components/TemplateComponents/ComponentList/ComponentList.vue')['default']
    ContentPad: typeof import('./components/ContentPad/ContentPad.vue')['default']
    Fit: typeof import('./components/Fit/Fit.vue')['default']
    FontList: typeof import('./components/FontList/FontList.vue')['default']
    ImageList: typeof import('./components/ImageList/ImageList.vue')['default']
    LateralBar: typeof import('./components/LateralBar/LateralBar.vue')['default']
    RecentProjects: typeof import('./components/RecentProjects/RecentProjects.vue')['default']
    RenderedTemplate: typeof import('./components/RenderedTemplate/RenderedTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeInput: typeof import('./components/SizeInput/SizeInput.vue')['default']
    TemplateComponentEditor: typeof import('./components/TemplateComponents/ComponentList/TemplateComponentEditor/TemplateComponentEditor.vue')['default']
    TemplateComponentRectangle: typeof import('./components/TemplateComponents/ComponentList/TemplateComponentEditor/ComponentTypes/Rectangle/TemplateComponentRectangle.vue')['default']
    TemplateComponents: typeof import('./components/TemplateComponents/TemplateComponents.vue')['default']
    TemplateList: typeof import('./components/TemplateList/TemplateList.vue')['default']
    TopNavigationBar: typeof import('./components/TopNavigationBar/TopNavigationBar.vue')['default']
  }
}
