/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./components/AlertDialog/AlertDialog.vue')['default']
    AutocompleteInput: typeof import('./components/AutocompleteInput/AutocompleteInput.vue')['default']
    CardComponentEditor: typeof import('./components/CardComponents/CardComponentEditor/CardComponentEditor.vue')['default']
    CardComponents: typeof import('./components/CardComponents/CardComponents.vue')['default']
    CardList: typeof import('./components/CardList/CardList.vue')['default']
    CardSelector: typeof import('./components/PipelineOptions/CardSelector/CardSelector.vue')['default']
    ColorInput: typeof import('./components/ColorInput/ColorInput.vue')['default']
    ColorPaletteEditor: typeof import('./components/ColorPaletteEditor/ColorPaletteEditor.vue')['default']
    ComponentList: typeof import('./components/TemplateComponents/ComponentList/ComponentList.vue')['default']
    ContentPad: typeof import('./components/ContentPad/ContentPad.vue')['default']
    ExpandButton: typeof import('./components/ExpandButton/ExpandButton.vue')['default']
    ExportPipelineCard: typeof import('./components/ExportPipelineList/ExportPipelineCard.vue')['default']
    ExportPipelineList: typeof import('./components/ExportPipelineList/ExportPipelineList.vue')['default']
    Filterbar: typeof import('./components/FilterBar/Filterbar.vue')['default']
    Fit: typeof import('./components/Fit/Fit.vue')['default']
    FontList: typeof import('./components/FontList/FontList.vue')['default']
    ImageList: typeof import('./components/ImageList/ImageList.vue')['default']
    InspectArea: typeof import('./components/InspectArea/InspectArea.vue')['default']
    LateralBar: typeof import('./components/LateralBar/LateralBar.vue')['default']
    NameField: typeof import('./components/NameField/NameField.vue')['default']
    PipelineOptions: typeof import('./components/PipelineOptions/PipelineOptions.vue')['default']
    PipelineSizeFields: typeof import('./components/PipelineOptions/PipelineSizeFields/PipelineSizeFields.vue')['default']
    RecentProjects: typeof import('./components/RecentProjects/RecentProjects.vue')['default']
    RenderedCard: typeof import('./components/RenderedCard/RenderedCard.vue')['default']
    RenderedComponent: typeof import('./components/RenderedComponent/RenderedComponent.vue')['default']
    RenderedTemplate: typeof import('./components/RenderedTemplate/RenderedTemplate.vue')['default']
    ResourceTree: typeof import('./components/ResourceTree/ResourceTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeInput: typeof import('./components/SizeInput/SizeInput.vue')['default']
    TemplateComponentEditor: typeof import('./components/TemplateComponents/ComponentList/TemplateComponentEditor/TemplateComponentEditor.vue')['default']
    TemplateComponentImage: typeof import('./components/TemplateComponents/ComponentList/TemplateComponentEditor/ComponentTypes/Image/TemplateComponentImage.vue')['default']
    TemplateComponentRectangle: typeof import('./components/TemplateComponents/ComponentList/TemplateComponentEditor/ComponentTypes/Rectangle/TemplateComponentRectangle.vue')['default']
    TemplateComponents: typeof import('./components/TemplateComponents/TemplateComponents.vue')['default']
    TemplateComponentText: typeof import('./components/TemplateComponents/ComponentList/TemplateComponentEditor/ComponentTypes/Text/TemplateComponentText.vue')['default']
    TemplateHandlers: typeof import('./components/TemplateHandlers/TemplateHandlers.vue')['default']
    TemplateList: typeof import('./components/TemplateList/TemplateList.vue')['default']
    TemplateSelector: typeof import('./components/TemplateSelector/TemplateSelector.vue')['default']
    TextField: typeof import('./components/TemplateComponents/ComponentList/TemplateComponentEditor/ComponentTypes/Text/TextField/TextField.vue')['default']
    ToogleButton: typeof import('./components/ToogleButton/ToogleButton.vue')['default']
    TopNavigationBar: typeof import('./components/TopNavigationBar/TopNavigationBar.vue')['default']
    ValueInput: typeof import('./components/ValueInput/ValueInput.vue')['default']
  }
}
