name: Deploy

on:
    push:
        branches: ['main']

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        if: "!contains(github.ref_name, 'release-please')"
        runs-on: windows-latest
        steps:
            - uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.DEPLOY_TOKEN }}
                  release-type: simple

            - name: Checkout code
              if: ${{ steps.release.outputs.release_created }}
              uses: actions/checkout@v4

            - name: Set up Node.js
              if: ${{ steps.release.outputs.release_created }}
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              if: ${{ steps.release.outputs.release_created }}
              run: npm ci

            - name: Update version in package.json
              if: ${{ steps.release.outputs.release_created }}
              run: |
                  npm version ${GITHUB_REF_NAME}

            - name: Build project
              if: ${{ steps.release.outputs.release_created }}
              run: npm run build

            - name: Upload windows installer
              if: ${{ steps.release.outputs.release_created }}
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
              run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist/vitral-windows-installer.exe

            - name: Upload windows portable
              if: ${{ steps.release.outputs.release_created }}
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
              run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist/vitral-windows-portable.exe

    linux-deploy:
        if: ${{ steps.release.outputs.release_created }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Upload linux package
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
              run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist/vitral-linux.deb
