name: Release

on:
    push:
        branches: ['main']

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: windows-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.DEPLOY_TOKEN }}
                  release-type: node
    deploy:
        if: ${{ needs.release-please.outputs.release_created }}
        needs:
            - release-please
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            upload: true
            uploadTarget: ${{ steps.release.outputs.tag_name }}

